<?php

namespace AppBundle\Repository;

/**
 * QualificationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QualificationsRepository extends \Doctrine\ORM\EntityRepository
{
}
